<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3b6a17a7-7570-42d9-b23f-2c00148a5bcb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Grpc" Version="2.46.6" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.69.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	<Protobuf Include="Protos\AuthorsService.proto" GrpcServices="Server" />
	<Protobuf Include="Protos\ReadersService.proto" GrpcServices="Server" />
	<Protobuf Include="Protos\BooksService.proto" GrpcServices="Server" />	  
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\Implementation\" />
    <Folder Include="Config\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\Interfaces\" />
    <Folder Include="Controllers\" />
    <Folder Include="Repository\" />
  </ItemGroup>

</Project>
