syntax = "proto3";

option csharp_namespace = "WEB.API.Protos.Books";

// Books
service BooksService {
  rpc GetBook (GetBookRequest) returns (GetBookResponse);
  rpc CreateBook (CreateBookRequest) returns (CreateBookResponse);
  rpc UpdateBook (UpdateBookRequest) returns (UpdateBookResponse);
  rpc DeleteBook (DeleteBookRequest) returns (DeleteBookResponse);
  rpc GetAllBooks (BooksEmptyRequest) returns (GetAllBooksResponse);
}

message GetBookRequest {
  int32 id = 1;
}

message GetBookResponse {
  Book book = 1;
}

message CreateBookRequest {
  string title = 1;
  int32 authorId = 2;
  int32 publisherId = 3;
  uint32 publisherYear = 4;
  string libraryLocation = 5;
}

message CreateBookResponse {
  Book book = 1;
}

message UpdateBookRequest {
  int32 id = 1;
  string title = 2;
  int32 authorId = 3;
  int32 publisherId = 4;
  uint32 publisherYear = 5;
  string libraryLocation = 6;
}

message UpdateBookResponse {
  Book book = 1;
}

message GetAllBooksResponse {
  repeated Book books = 1;
}

message Book {
  int32 id = 1;
  string title = 2;
  int32 authorId = 3;
  int32 publisherId = 4;
  uint32 publisherYear = 5;
  string libraryLocation = 6;
}

// General messages
message BooksEmptyRequest {}

message DeleteBookRequest {
  int32 id = 1; // The ID of the book to delete
}

message DeleteBookResponse {
  bool success = 1; // Indicates if the delete operation was successful
}
