syntax = "proto3";

option csharp_namespace = "WEB.API.Protos.BookIssues";

// Book Issues
service BookIssuesService {
  rpc GetBookIssue (GetBookIssueRequest) returns (GetBookIssueResponse);
  rpc CreateBookIssue (CreateBookIssueRequest) returns (CreateBookIssueResponse);
  rpc UpdateBookIssue (UpdateBookIssueRequest) returns (UpdateBookIssueResponse);
  rpc DeleteBookIssue (DeleteBookIssueRequest) returns (DeleteBookIssueResponse);
  rpc GetAllBookIssues (BookIssuesEmptyRequest) returns (GetAllBookIssuesResponse);
  rpc GetBookIssuesByReader (GetBookIssuesByReaderRequest) returns (GetBookIssuesByReaderResponse);
  rpc ReturnBookIssues (ReturnBookIssuesRequest) returns (ReturnBookIssuesResponse);
  rpc GetOverdueBookIssues (BookIssuesEmptyRequest) returns (GetOverdueBookIssuesResponse); // Новый метод
}

// Сообщения для метода GetOverdueBookIssues
message GetOverdueBookIssuesResponse {
  repeated BookIssue bookIssues = 1; // Список просроченных выдач
}

// Сообщения для других методов
message GetBookIssueRequest {
  int32 id = 1;
}
 
message GetBookIssueResponse {
  BookIssue bookIssue = 1;
}

message CreateBookIssueRequest {
  int32 bookId = 1;
  int32 readerId = 2;
  string issueDate = 3;
  string expectedReturnDate = 4;
  string actualReturnDate = 5;
}

message CreateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message UpdateBookIssueRequest {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}

message UpdateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message GetAllBookIssuesResponse {
  repeated BookIssue bookIssues = 1;
}

message BookIssue {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}

// General messages
message BookIssuesEmptyRequest {}

message DeleteBookIssueRequest {
  int32 id = 1; // The ID of the book issue to delete
}

message DeleteBookIssueResponse {
  bool success = 1; // Indicates if the delete operation was successful
}

// Новый запрос и ответ для возврата книги
message ReturnBookIssuesRequest {
  int32 id = 1; // ID записи о выдаче книги
  string actualReturnDate = 2; // Фактическая дата возврата
}

message ReturnBookIssuesResponse {
  BookIssue bookIssue = 1; // Обновленная запись о выдаче книги
}

// Новый запрос и ответ для фильтрации по ID читателя
message GetBookIssuesByReaderRequest {
  int32 readerId = 1; // ID читателя; может быть пустым (0)
}

message GetBookIssuesByReaderResponse {
  repeated BookIssue bookIssues = 1; // Список записей о выдаче книг
}