syntax = "proto3";

option csharp_namespace = "WEB.API.Protos";

// Book Issues
service BookIssueService {
  rpc GetBookIssue (GetBookIssueRequest) returns (GetBookIssueResponse);
  rpc CreateBookIssue (CreateBookIssueRequest) returns (CreateBookIssueResponse);
  rpc UpdateBookIssue (UpdateBookIssueRequest) returns (UpdateBookIssueResponse);
  rpc DeleteBookIssue (DeleteBookIssueRequest) returns (DeleteBookIssueResponse);
  rpc GetAllBookIssues (EmptyRequest) returns (GetAllBookIssuesResponse);
}

message GetBookIssueRequest {
  int32 id = 1;
}

message GetBookIssueResponse {
  BookIssue bookIssue = 1;
}

message CreateBookIssueRequest {
  int32 bookId = 1;
  int32 readerId = 2;
  string issueDate = 3;
  string expectedReturnDate = 4;
  string actualReturnDate = 5;
}

message CreateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message UpdateBookIssueRequest {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}

message UpdateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message GetAllBookIssuesResponse {
  repeated BookIssue bookIssues = 1;
}

message BookIssue {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}

// General messages
message EmptyRequest {}

message DeleteBookIssueRequest {
  int32 id = 1; // The ID of the book issue to delete
}

message DeleteBookIssueResponse {
  bool success = 1; // Indicates if the delete operation was successful
}
