syntax = "proto3";

option csharp_namespace = "WEB.API.Protos";

// Общий сервис
service LibraryService {
  // Books
  rpc GetBook (GetBookRequest) returns (GetBookResponse);
  rpc CreateBook (CreateBookRequest) returns (CreateBookResponse);
  rpc UpdateBook (UpdateBookRequest) returns (UpdateBookResponse);
  rpc DeleteBook (DeleteRequest) returns (DeleteResponse);
  rpc GetAllBooks (EmptyRequest) returns (GetAllBooksResponse);

  // Authors
  rpc GetAuthor (GetAuthorRequest) returns (GetAuthorResponse);
  rpc CreateAuthor (CreateAuthorRequest) returns (CreateAuthorResponse);
  rpc UpdateAuthor (UpdateAuthorRequest) returns (UpdateAuthorResponse);
  rpc DeleteAuthor (DeleteRequest) returns (DeleteResponse);
  rpc GetAllAuthors (EmptyRequest) returns (GetAllAuthorsResponse);

  // Readers
  rpc GetReader (GetReaderRequest) returns (GetReaderResponse);
  rpc CreateReader (CreateReaderRequest) returns (CreateReaderResponse);
  rpc UpdateReader (UpdateReaderRequest) returns (UpdateReaderResponse);
  rpc DeleteReader (DeleteRequest) returns (DeleteResponse);
  rpc GetAllReaders (EmptyRequest) returns (GetAllReadersResponse);

  // Publishers
  rpc GetPublisher (GetPublisherRequest) returns (GetPublisherResponse);
  rpc CreatePublisher (CreatePublisherRequest) returns (CreatePublisherResponse);
  rpc UpdatePublisher (UpdatePublisherRequest) returns (UpdatePublisherResponse);
  rpc DeletePublisher (DeleteRequest) returns (DeleteResponse);
  rpc GetAllPublishers (EmptyRequest) returns (GetAllPublishersResponse);

  // BookIssues
  rpc GetBookIssue (GetBookIssueRequest) returns (GetBookIssueResponse);
  rpc CreateBookIssue (CreateBookIssueRequest) returns (CreateBookIssueResponse);
  rpc UpdateBookIssue (UpdateBookIssueRequest) returns (UpdateBookIssueResponse);
  rpc DeleteBookIssue (DeleteRequest) returns (DeleteResponse);
  rpc GetAllBookIssues (EmptyRequest) returns (GetAllBookIssuesResponse);
}

// Общие сообщения
message EmptyRequest {}

message DeleteRequest {
  int32 id = 1;
}

message DeleteResponse {
  bool success = 1;
}

// Books
message GetBookRequest {
  int32 id = 1;
}

message GetBookResponse {
  Book book = 1;
}

message CreateBookRequest {
  string title = 1;
  int32 authorId = 2;
  int32 publisherId = 3;
  uint32 publisherYear = 4;
  string libraryLocation = 5;
}

message CreateBookResponse {
  Book book = 1;
}

message UpdateBookRequest {
  int32 id = 1;
  string title = 2;
  int32 authorId = 3;
  int32 publisherId = 4;
  uint32 publisherYear = 5;
  string libraryLocation = 6;
}

message UpdateBookResponse {
  Book book = 1;
}

message GetAllBooksResponse {
  repeated Book books = 1;
}

message Book {
  int32 id = 1;
  string title = 2;
  int32 authorId = 3;
  int32 publisherId = 4;
  uint32 publisherYear = 5;
  string libraryLocation = 6;
}

// Authors
message GetAuthorRequest {
  int32 id = 1;
}

message GetAuthorResponse {
  Author author = 1;
}

message CreateAuthorRequest {
  string firstName = 1;
  string lastName = 2;
}

message CreateAuthorResponse {
  Author author = 1;
}

message UpdateAuthorRequest {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
}

message UpdateAuthorResponse {
  Author author = 1;
}

message GetAllAuthorsResponse {
  repeated Author authors = 1;
}

message Author {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
}

// Readers
message GetReaderRequest {
  int32 id = 1;
}

message GetReaderResponse {
  Reader reader = 1;
}

message CreateReaderRequest {
  string firstName = 1;
  string lastName = 2;
  string birthDayDate = 3;
  string gender = 4;
  string educationLevel = 5;
}

message CreateReaderResponse {
  Reader reader = 1;
}

message UpdateReaderRequest {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
  string birthDayDate = 4;
  string gender = 5;
  string educationLevel = 6;
}

message UpdateReaderResponse {
  Reader reader = 1;
}

message GetAllReadersResponse {
  repeated Reader readers = 1;
}

message Reader {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
  string birthDayDate = 4;
  string gender = 5;
  string educationLevel = 6;
}

// Publishers
message GetPublisherRequest {
  int32 id = 1;
}

message GetPublisherResponse {
  Publisher publisher = 1;
}

message CreatePublisherRequest {
  string name = 1;
}

message CreatePublisherResponse {
  Publisher publisher = 1;
}

message UpdatePublisherRequest {
  int32 id = 1;
  string name = 2;
}

message UpdatePublisherResponse {
  Publisher publisher = 1;
}

message GetAllPublishersResponse {
  repeated Publisher publishers = 1;
}

message Publisher {
  int32 id = 1;
  string name = 2;
}

// BookIssues
message GetBookIssueRequest {
  int32 id = 1;
}

message GetBookIssueResponse {
  BookIssue bookIssue = 1;
}

message CreateBookIssueRequest {
  int32 bookId = 1;
  int32 readerId = 2;
  string issueDate = 3;
  string expectedReturnDate = 4;
  string actualReturnDate = 5;
}

message CreateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message UpdateBookIssueRequest {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}

message UpdateBookIssueResponse {
  BookIssue bookIssue = 1;
}

message GetAllBookIssuesResponse {
  repeated BookIssue bookIssues = 1;
}

message BookIssue {
  int32 id = 1;
  int32 bookId = 2;
  int32 readerId = 3;
  string issueDate = 4;
  string expectedReturnDate = 5;
  string actualReturnDate = 6;
}
