syntax = "proto3";

option csharp_namespace = "WEB.API.Protos";

// Readers
service ReaderService {
  rpc GetReader (GetReaderRequest) returns (GetReaderResponse);
  rpc CreateReader (CreateReaderRequest) returns (CreateReaderResponse);
  rpc UpdateReader (UpdateReaderRequest) returns (UpdateReaderResponse);
  rpc DeleteReader (DeleteReaderRequest) returns (DeleteReaderResponse);
  rpc GetAllReaders (EmptyRequest) returns (GetAllReadersResponse);
}

message GetReaderRequest {
  int32 id = 1;
}

message GetReaderResponse {
  Reader reader = 1;
}

message CreateReaderRequest {
  string firstName = 1;
  string lastName = 2;
  string birthDayDate = 3;
  string gender = 4;
  string educationLevel = 5;
}

message CreateReaderResponse {
  Reader reader = 1;
}

message UpdateReaderRequest {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
  string birthDayDate = 4;
  string gender = 5;
  string educationLevel = 6;
}

message UpdateReaderResponse {
  Reader reader = 1;
}

message GetAllReadersResponse {
  repeated Reader readers = 1;
}

message Reader {
  int32 id = 1;
  string firstName = 2;
  string lastName = 3;
  string birthDayDate = 4;
  string gender = 5;
  string educationLevel = 6;
}

// General messages
message EmptyRequest {}

message DeleteReaderRequest {
  int32 id = 1; // The ID of the reader to delete
}

message DeleteReaderResponse {
  bool success = 1; // Indicates if the delete operation was successful
}
